baseurl = "http://blog.homfen.me/"
title = "Homfen's blog"
languageCode = "en-us"
theme = "hugo-base16-theme"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = ""
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = "Welcome to my blog."

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
